### ISSUE TITLE
Send over conversation history to gpt and get a stream of data back

### ISSUE THREAD

**Issue by BossCodersHQ** [BossCodersHQ/mock-ai-interviewer#26]
## Stage 1
- [X] Get a connection to GPT working with API Tokens
- [X] Get it to stream data back

## Stage 2
Create a function that:
- [x] Gets current conversation history from mongo DB
- [x] Sends to ChatGPT & streams response using SSE (Server Side Events)
  - For now can just log/print the response
- After finishing there should be a function to save the full response as entry in mongo db
